apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-azure-kv
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.azure.userAssignedIdentityID | quote }}
    keyvaultName: {{ .Values.azure.keyVaultName | quote }}
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: groq-api-key
          objectType: secret
          objectVersion: ""
    tenantId: {{ .Values.azure.tenantId | quote }}
  secretObjects:
  - secretName: devops-assistant-secrets
    type: Opaque
    data:
    - objectName: groq-api-key
      key: groq-api-key
