name: Build and Deploy to AKS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  ACR_NAME: adityazuretest
  RESOURCE_GROUP: Azure_Practice
  CLUSTER_NAME: adityaclustertest
  CHART_PATH: ./helm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Backend Image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - run: |
          docker build backend -t ${{ env.ACR_NAME }}.azurecr.io/devops-assistant-backend:${{ github.sha }}
          docker push ${{ env.ACR_NAME }}.azurecr.io/devops-assistant-backend:${{ github.sha }}

      - name: Build and Push Frontend Image
        run: |
          docker build frontend -t ${{ env.ACR_NAME }}.azurecr.io/devops-assistant-frontend:${{ github.sha }} \
            --build-arg VITE_AZURE_CLIENT_ID=cd7eeb97-7ffd-4369-bd04-c5b76df938ce \
            --build-arg VITE_AZURE_TENANT_ID=ac371305-0f1d-47d3-8dd8-3d5f83dccf8b \
            --build-arg VITE_API_URL=https://adityaapim.azure-api.net/devops-assistant \
            --build-arg VITE_APIM_SUBSCRIPTION_KEY=ca20556ea1d5419eacdee15ecd59225b
          docker push ${{ env.ACR_NAME }}.azurecr.io/devops-assistant-frontend:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install kubelogin
        run: |
          curl -Lo kubelogin.zip https://github.com/Azure/kubelogin/releases/download/v0.1.6/kubelogin-linux-amd64.zip
          unzip kubelogin.zip -d kubelogin
          sudo mv kubelogin/bin/linux_amd64/kubelogin /usr/local/bin/kubelogin
          kubelogin --version

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.CLUSTER_NAME }} \
            --overwrite-existing

      - name: Convert kubeconfig for AAD
        run: |
          kubelogin convert-kubeconfig --login azurecli

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: "v3.12.0"

      - name: Deploy to AKS
        run: |
          helm upgrade --install devops-assistant ${{ env.CHART_PATH }} \
            --set backend.image.tag=${{ github.sha }} \
            --set frontend.image.tag=${{ github.sha }}
