name: Build and Deploy to AKS

on:
    push:
        branches: ["main"]
    workflow_dispatch:

env:
    ACR_NAME: adityazuretest
    RESOURCE_GROUP: Azure_Practice
    CLUSTER_NAME: adityaclustertest
    CHART_PATH: ./helm

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Azure Login
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Build and Push Backend Image
              uses: azure/docker-login@v1
              with:
                  login-server: ${{ env.ACR_NAME }}.azurecr.io
                  username: ${{ secrets.ACR_USERNAME }}
                  password: ${{ secrets.ACR_PASSWORD }}

            - run: |
                  docker build backend -t ${{ env.ACR_NAME }}.azurecr.io/devops-assistant-backend:${{ github.sha }}
                  docker push ${{ env.ACR_NAME }}.azurecr.io/devops-assistant-backend:${{ github.sha }}

            - name: Build and Push Frontend Image
              run: |
                  docker build frontend -t ${{ env.ACR_NAME }}.azurecr.io/devops-assistant-frontend:${{ github.sha }} \
                    --build-arg VITE_AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }} \
                    --build-arg VITE_AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
                  docker push ${{ env.ACR_NAME }}.azurecr.io/devops-assistant-frontend:${{ github.sha }}

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Azure Login
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Get AKS Credentials
              uses: azure/aks-set-context@v3
              with:
                  resource-group: ${{ env.RESOURCE_GROUP }}
                  cluster-name: ${{ env.CLUSTER_NAME }}

            - name: Deploy to AKS
              uses: azure/k8s-deploy@v4
              with:
                  action: deploy
                  manifests: |
                      ${{ env.CHART_PATH }}
                  images: |
                      ${{ env.ACR_NAME }}.azurecr.io/devops-assistant-backend:${{ github.sha }}
                      ${{ env.ACR_NAME }}.azurecr.io/devops-assistant-frontend:${{ github.sha }}
                  namespace: default
